#cloud-config
package_update: true
packages:
  - curl
  - unzip
  - apt-transport-https
  - lsb-release
  - gnupg

runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash

  # Wait for managed identity to be ready
  #- sleep 15

  # Login with system-assigned managed identity
  #- az login --identity --allow-no-subscriptions

  # Optionally show current user
  #- az account show

  # - az keyvault secret show --vault-name my-vault --name example-secret
